-- schema.sql - Database Schema setup for Supabase
-- Paste this script into your Supabase SQL Editor to create tables, triggers, and Row Level Security (RLS) policies.

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1. Create User Profiles table mapping authentication records to roles
CREATE TABLE IF NOT EXISTS public.user_profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'readonly' CHECK (role IN ('admin', 'editor', 'readonly')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on user_profiles
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;

-- 2. Create Firearms Table
CREATE TABLE IF NOT EXISTS public.firearms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner TEXT NOT NULL DEFAULT 'N/A',
  type TEXT NOT NULL DEFAULT 'Rifle',
  manufacturer TEXT NOT NULL,
  model TEXT NOT NULL,
  caliber TEXT NOT NULL,
  serial_number TEXT DEFAULT 'N/A',
  action_type TEXT DEFAULT 'N/A',
  sight_type TEXT DEFAULT 'N/A',
  value NUMERIC NOT NULL DEFAULT 0,
  condition TEXT NOT NULL DEFAULT 'Good',
  location TEXT DEFAULT 'N/A',
  date_acquired TEXT DEFAULT 'N/A',
  image TEXT DEFAULT '', -- Stores Base64 images
  notes TEXT DEFAULT '',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

-- Enable RLS on firearms
ALTER TABLE public.firearms ENABLE ROW LEVEL SECURITY;

-- 3. Trigger Function to automatically create user profiles upon signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.user_profiles (id, email, role)
  VALUES (
    new.id,
    new.email,
    CASE 
      WHEN new.email = 'e10278@hotmail.com' THEN 'admin'
      ELSE 'readonly'
    END
  )
  ON CONFLICT (id) DO UPDATE
  SET email = excluded.email; -- Avoid duplicate key errors if profiles are created manually
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to execute on signup
CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 4. Helper Function: Check if user is Administrator
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean SECURITY DEFINER AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.user_profiles
    WHERE id = auth.uid() AND role = 'admin'
  );
END;
$$ LANGUAGE plpgsql;

-- Helper Function: Check if user has write/edit permissions (admin or editor)
CREATE OR REPLACE FUNCTION public.check_user_write_access()
RETURNS boolean SECURITY DEFINER AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.user_profiles
    WHERE id = auth.uid() AND role IN ('admin', 'editor')
  );
END;
$$ LANGUAGE plpgsql;

-- 5. RPC Function: Administrator custom user creation (bypasses email validation)
CREATE OR REPLACE FUNCTION public.admin_create_user(
  user_email TEXT,
  user_password TEXT,
  user_role TEXT
)
RETURNS json SECURITY DEFINER AS $$
DECLARE
  new_user_id UUID;
  result json;
BEGIN
  -- Enforce role restriction: only admins can call this function
  IF NOT EXISTS (
    SELECT 1 FROM public.user_profiles
    WHERE id = auth.uid() AND role = 'admin'
  ) THEN
    RAISE EXCEPTION 'Access Denied: Only administrators can create users.';
  END If;

  -- Create authentication user record directly
  INSERT INTO auth.users (
    instance_id,
    id,
    email,
    encrypted_password,
    email_confirmed_at,
    raw_app_meta_data,
    raw_user_meta_data,
    created_at,
    updated_at,
    role,
    confirmation_token,
    email_change,
    email_change_token_new,
    recovery_token
  )
  VALUES (
    '00000000-0000-0000-0000-000000000000',
    gen_random_uuid(),
    user_email,
    crypt(user_password, gen_salt('bf')),
    now(),
    '{"provider":"email","providers":["email"]}',
    '{}',
    now(),
    now(),
    'authenticated',
    '',
    '',
    '',
    ''
  )
  RETURNING id INTO new_user_id;

  -- Explicitly update their role in user_profiles (overrides the trigger default)
  UPDATE public.user_profiles
  SET role = user_role
  WHERE id = new_user_id;

  result := json_build_object('success', true, 'userId', new_user_id);
  RETURN result;
EXCEPTION
  WHEN OTHERS THEN
    result := json_build_object('success', false, 'error', SQLERRM);
    RETURN result;
END;
$$ LANGUAGE plpgsql;

-- 6. Row Level Security Policies for Firearms table
CREATE POLICY "Allow authenticated reads on firearms" 
ON public.firearms FOR SELECT 
TO authenticated 
USING (true);

CREATE POLICY "Allow editor inserts on firearms" 
ON public.firearms FOR INSERT 
TO authenticated 
WITH CHECK (public.check_user_write_access());

CREATE POLICY "Allow editor updates on firearms" 
ON public.firearms FOR UPDATE 
TO authenticated 
USING (public.check_user_write_access());

CREATE POLICY "Allow editor deletes on firearms" 
ON public.firearms FOR DELETE 
TO authenticated 
USING (public.check_user_write_access());

-- 7. Row Level Security Policies for User Profiles table
CREATE POLICY "Allow authenticated read profiles" 
ON public.user_profiles FOR SELECT 
TO authenticated 
USING (true);

CREATE POLICY "Allow admin full control on profiles" 
ON public.user_profiles FOR ALL 
TO authenticated 
USING (public.is_admin());
